# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'TravelPlanner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    pod 'Alamofire', '~> 4.0'
    pod 'Cosmos', '~> 11.0’
    pod 'KCFloatingActionButton', '~> 2.2'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'GooglePlacePicker', '= 2.3.0'
    pod 'GooglePlaces', '= 2.3.0'
    pod 'GoogleMaps', '= 2.3.0'
    pod 'SwiftyJSON'
    pod ‘YMCalendar’
    pod 'JKSteppedProgressBar'
    pod 'GooglePlacesSearchController'
    pod 'D2PDatePicker'
    pod 'AACarousel'
    pod 'Kingfisher', '~> 4.0'
    pod 'SwipeCellKit'
    pod 'CRRefresh'
    pod 'SDWebImage', '~> 4.0'
  # Pods for TravelPlanner

end
